kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml

images:
- name: gitops
  newName: jaksonsneider/gitops
  newTag: 52b7405aaeb0af1f8e9c53bdc42461734b334e57
