kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml

images:
- name: gitops
  newName: jaksonsneider/gitops
  newTag: 19ed87f3d4aebfe6312b90aaae2ffa75a3d0342a
