kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment
- service

images:
- name: gitops
  newName: jaksonsneider/gitops
  newTag: 863d690f609818a9f968af4de8af788d9b7c8c2c
