kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml

images:
- name: gitops
  newName: jaksonsneider/gitops
  newTag: 713501085723c2712adbb7079f7706ebf8e23fbb
