kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml

images:
- name: gitops
  newName: jaksonsneider/gitops
  newTag: 11eb92762004027847ed5237d29d51bf4c3178fd
